config/routes.rb
Rails.application.routes.draw do
  get 'games/save'
    # Users routes
    resources :users
    get 'login', :to => 'users#get_login_form'
    post 'login', :to => 'users#login'
    get 'logout', :to => 'users#logout'
    get 'users/:id/editpassword', :to => 'users#edit_password', :as => 'edit_password'
    put 'users/:id/password', :to => 'users#update_password', :as => 'update_password'
    # Leagues routes
    get 'leagues', :to => 'leagues#index', :as => 'leagues'
    get 'leagues/new', :to => 'leagues#new', :as => 'new_league'
    post 'leagues', :to => 'leagues#create', :as => 'create_league'
    get 'leagues/:id', :to => 'leagues#show', :as => 'show_league'
    delete 'leagues/:id', :to => 'leagues#destroy', :as => 'destroy_league'
    get 'leagues/add_contestant/:id/:user_id', :to => 'leagues#add_contestant', :as => 'add_contestant'
    get 'leagues/close/:id', :to => 'leagues#close', :as => 'close_league'
    get 'leagues/open/:id', :to => 'leagues#open', :as => 'open_league'
    # Games reoutes
    get 'games/:id', :to => 'games#save', :as => 'save_game_score'
    put 'games/:id', :to => 'games#update', :as => 'update_game'
    # Other routes
    root "welcome#index"
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/league.rb
class League < ApplicationRecord
  belongs_to :user, :class_name => 'User'
  has_many :contestants, :class_name => 'Contestant'
  has_many :games, :class_name => 'Game'

  def destroy_all
    self.contestants.each do |c|
      c.destroy
    end
    self.games.each do |g|
      g.destroy
    end
    self.destroy
  end

  def is_user_sign_in(user_id)
    self.contestants.each do |c|
        if c.user[:id] == user_id
            return true
        end
    end
    return false
  end

  def is_full
    return self[:max_contestants] == self.contestants.count
  end

  def can_user_register(user_id)
    return !self.is_closed &&  
      user_id != self.user.id &&
      !self.is_user_sign_in(user_id) && 
      !self.is_full 
  end

  def create_empty(name, user, max_contestants)
    new_league = League.create({
      :name => name,
      :user => user,
      :max_contestants => max_contestants,
      :is_closed => false,
      :is_finished => false,
      :games_left => nil
    })
    return new_league
  end

  def decrement_games_left
    self.games_left -= 1
    if self.games_left < 1
      self.is_finished = true
      get_winner
    end
    self.save
  end

  def get_winner
    winner = self.contestants[0]
    self.contestants.each do |c|
      if c.points > winner.points
        winner = c
      end
    end
    winner.has_won = true
    winner.save
  end
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
    include LeaguesHelper

    def index
        @leagues = League.all
    end

    def new
        if session[:current_user_id] == nil
            redirect_to root_path
            return
        end
    end

    def create
        if session[:current_user_id] == nil
            redirect_to root_path
            return
        end
        if params.require(:league)[:name] == ""
            flash[:error] = "League name is empty."
            redirect_to new_league_path
            return
        end
        @league = League.create(league_params)
        redirect_to leagues_path
    end

    def destroy
        @league = League.find(params[:id])
        if @league.user.id != session[:current_user_id]
            redirect_to show_league_path(@league)
            return
        end
        @league.destroy_all
        redirect_to leagues_path
    end

    def show
        @league = League.find(params[:id])
    end

    def add_contestant
        @league = League.find(params[:id])
        if @league.is_full 
            redirect_to leagues_path
            return
        end
        @user = User.find(params[:user_id])
        if @league == nil || @user == nil || @league.is_user_sign_in(@user[:id])
            redirect_to leagues_path
            return
        end
        @contestant = Contestant.create({
            :league => @league,
            :user => @user,
            :has_won => false,
            :points => 0
        })
        redirect_to show_league_path(@league)
    end

    def close
        @league = League.find(params[:id])
        @league.is_closed = true
        @league.save
        create_games(@league)
        redirect_to show_league_path(@league)
    end

    def open
        @league = League.find(params[:id])
        @league.is_closed = false
        destroy_all_games(@league)
        @league.save
        redirect_to show_league_path(@league)
    end

    private
        def league_params
            form_params = params.require(:league)
            return {
                    :name => form_params[:name], 
                    :user => User.find(session[:current_user_id]),
                    :max_contestants => form_params[:max_contestants]
            }
        end
end

app/helpers/leagues_helper.rb
module LeaguesHelper
    def create_games(league)
        games_count = 0
        (0..league.contestants.count-2).to_a.each do |i|
            (i+1..league.contestants.count-1).to_a.each do |j|
                create_game(league.contestants[i], league.contestants[j], league)
                games_count += 1
            end
        end
        league.games_left = games_count
        league.save
    end

    def create_game(player1, player2, league)
        Game.create({
            :player_1 => player1.user.login,
            :player_2 => player2.user.login,
            :league => league,
            :is_finished => false,
            :score_1 => 0,
            :score_2 => 0
        })
    end

    def destroy_all_games(league)
        league.games.each do |g|
            g.destroy
        end
        league.contestants.each do |c|
            c.destroy
        end
    end
end

app/views/leagues/index.html.erb
<div class="container">         
  <table class="table table-dark table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Owner</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
        <% @leagues.each do |l| %>
        <tr>
            <td><%= l.name %></td>
            <td><%= l.user.login %></td>
            <td class="action-buttons">
                <div class="btn-group">
                  <%= link_to "Show", show_league_path(l), :class => "btn btn-success" %>
                  <% if l.can_user_register(session[:current_user_id]) %>
                    <%= link_to "Participate", add_contestant_path(l, session[:current_user_id]), :class => "btn btn-success" %>
                  <% else %>
                    <a href="#" class="btn btn-success" disabled>Participate</a>
                  <% end %>
                </div>
            </td>
        </tr>
        <% end %>
    </tbody>
  </table>
</div>

app/views/leagues/new.html.erb
<div class="row  text-center"><h2>Create Your new League</h2></div>
<div class="row ">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <% if flash[:error] != nil %>
            <div class="alert alert-danger"><%= flash[:error] %></div>
        <% end %>
        <%= form_with scope: :league, url: create_league_path do |form| %>
            <div class="form-group">
                <%= form.label :name, "Name: ", class: "control-label" %>
                <%= form.text_field :name, class: "form-control", autofocus: "autofocus" %>
            </div>
            <div class="form-group">
                <%= form.label :max_contestants, "Maximum number of Contestants: ", class: "control-label" %> 
                <%= form.number_field :max_contestants, in: 2..30, class: "form-control" %>
            </div>
            <%= form.submit 'Create League', class: "btn btn-primary" %>
        <% end %>
    </div>
    <div class="col-md-2"></div>
</div>

app/views/leagues/show.html.erb
<div class="row">
    <h1><%= @league.name %></h1>
    <div class="btn-group">
        <% if @league.user.id == session[:current_user_id] %>
            <% if !@league.is_closed %>
                <%= link_to "Close Registrations", close_league_path(@league), :class => "btn btn-danger" %>
            <% else %>
                <%= link_to "Open Registrations", open_league_path(@league), :class => "btn btn-success" %>
            <% end %>
            <%= link_to "Delete League", destroy_league_path(@league), :class => "btn btn-danger",
                    :method => :delete, data: {:confirm => "Are You sure?", :title => "Delete #{@league.name}"} %>
        <% else %>
            <% if @league.can_user_register(session[:current_user_id]) %>
                <%= link_to "Participate", add_contestant_path(@league, session[:current_user_id]), :class => "btn btn-success" %>
            <% else %>
                <a href="#" class="btn btn-success" disabled>Participate</a>
            <% end %>
        <% end %>
    </div>
</div>
<% if @league.games_left != nil && @league.games_left < 1 %>
<div class="row"><h2>Winner:</h2></div>
<div class="row">
    <span class="glyphicon glyphicon-star"></span>
    <%= @league.contestants.where( :has_won => true ).first.user.login %>
    <span class="glyphicon glyphicon-star"></span>
</div>
<% end %>
<div class="row league-info-header">
    <button class="btn btn-info col-sm-12" type="button" 
            data-toggle="collapse" data-target="#participants-collapse" 
            aria-expanded="true" aria-controls="participants-collapse">
        <h5>Participants</h5>
    </button> 
</div>
<div class="row collapse" id="participants-collapse">
<% if @league.contestants.count > 0 %>
    <table class="table table-dark table-striped">
        <thead>
        <tr>
            <th>Nickname</th>
            <th>Email</th>
            <th>Points</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
            <% @league.contestants.each do |c| %>
            <tr>
                <td><%= c.user.login %></td>
                <td><%= c.user.email %></td>
                <td><%= c.points %></td>
                <td class="action-buttons">
                    <div class="btn-group">
                        <%= link_to "Show Profile", c.user, :class => "btn btn-success" %>
                    </div>
                </td>
            </tr>
            <% end %>
        </tbody>
    </table>
<% else %>
    No one has registered for this league for now.
<% end %>
</div>
<div class="row league-info-header">
    <button class="btn btn-info col-sm-12" type="button" 
            data-toggle="collapse" data-target="#games-collapse" 
            aria-expanded="true" aria-controls="games-collapse">
        <h5>Games</h5>
    </button> 
</div>
<div class="row collapse" id="games-collapse">
    <% if @league.user.id == session[:current_user_id] && !@league.is_closed %>
        Close registration to generate games for this league.
    <% elsif @league.games.count != 0 %>
        <table class="table table-dark table-striped">
            <thead>
            <tr>
                <th style="text-align: left;">Player 1</th>
                <th style="text-align: center;">Score</th>
                <th style="text-align: right;">Player 2</th>
            </tr>
            </thead>
            <tbody>
                <% @league.games.each do |g| %>
                <tr>
                    <td style="text-align: left;"><%= g.player_1 %></td>
                    <td style="text-align: center;">
                        <% if g.is_finished %>
                        <h4><%= g.score_1 %> - <%= g.score_2 %></h4>
                        <% elsif @league.user.id == session[:current_user_id] %>
                            <div class="btn-group">
                                <%= link_to "Finish and save score", save_game_score_path(g), :class => "btn btn-success" %>
                            </div>
                        <% else %>
                            <h4>No score yet</h4>
                        <% end %>
                    </td>
                    <td style="text-align: right"><%= g.player_2 %></td>
                </tr>
                <% end %>
            </tbody>
        </table>
    <% else  %>
        There are no games generated for this league.
    <% end %>
</div>