config/routes.rb
Rails.application.routes.draw do
  get 'games/save'
    # Users routes
    resources :users
    get 'login', :to => 'users#get_login_form'
    post 'login', :to => 'users#login'
    get 'logout', :to => 'users#logout'
    get 'users/:id/editpassword', :to => 'users#edit_password', :as => 'edit_password'
    put 'users/:id/password', :to => 'users#update_password', :as => 'update_password'
    # Leagues routes
    get 'leagues', :to => 'leagues#index', :as => 'leagues'
    get 'leagues/new', :to => 'leagues#new', :as => 'new_league'
    post 'leagues', :to => 'leagues#create', :as => 'create_league'
    get 'leagues/:id', :to => 'leagues#show', :as => 'show_league'
    delete 'leagues/:id', :to => 'leagues#destroy', :as => 'destroy_league'
    get 'leagues/add_contestant/:id/:user_id', :to => 'leagues#add_contestant', :as => 'add_contestant'
    get 'leagues/close/:id', :to => 'leagues#close', :as => 'close_league'
    get 'leagues/open/:id', :to => 'leagues#open', :as => 'open_league'
    # Games reoutes
    get 'games/:id', :to => 'games#save', :as => 'save_game_score'
    put 'games/:id', :to => 'games#update', :as => 'update_game'
    # Other routes
    root "welcome#index"
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    validates :login, uniqueness: true
    has_many :contestants, :class_name => 'Contestant'
    has_many :leagues, :class_name => 'League'

    require 'digest/md5'
    
    def getGravatarLink(size)
        emailHash = Digest::MD5.hexdigest(self[:email])
        return "https://www.gravatar.com/avatar/#{emailHash}?s=#{size}"
    end

    def securePassword
        self[:password] = Digest::MD5.hexdigest(self[:password])
    end

    def update_password(new_password)
        self.update :password => Digest::MD5.hexdigest(new_password)
    end

    def checkPassword(providedPassword)
        return self[:password] == Digest::MD5.hexdigest(providedPassword)
    end

    def destroy_all
        self.contestants.each do |c|
            c.destroy
        end
        self.leagues.each do |l|
            l.destroy_all
        end
        self.destroy
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
    end

    def login
        @user = User.find_by login: get_login
        if @user == nil || !@user.checkPassword(get_password)
            flash[:error] = "Invalid login or password."
            redirect_to login_path
            return
        end
        session[:current_user_id] = @user[:id]
        session[:current_user_name] = @user[:login]
        redirect_to root_path
    end

    def logout
        session[:current_user_id] = nil
        session[:current_user_name] = nil
        @user = nil
        redirect_to root_path
    end

    def get_login_form
    end

    def new
    end

    def edit
    end

    def edit_password
    end

    def create
        req_params = register_params
        if !password_check
            flash[:error] = "Passwords aren't the same. "
        end
        if req_params[:login] == ""
            init_error
            flash[:error] = flash[:error] + "Login is empty. "
        end
        if req_params[:password] == ""
            init_error
            flash[:error] = flash[:error] + "Password is empty. "
        end
        if req_params[:email] == ""
            init_error
            flash[:error] = flash[:error] + "Email is empty. "
        end
        if flash[:error] != nil
            redirect_to new_user_path
        return
        end
        @user = User.new(register_params)
        unless @user.valid?
            flash[:error] = "Such user already exists. Try other login."
            redirect_to new_user_path
            return
        end
        @user.securePassword
        @user.save
        session[:current_user_id] = @user[:id]
        session[:current_user_name] = @user[:login]
        redirect_to @user
    end

    def show
        @user = User.find(params[:id])
        @leagues = League.where :user => @user
    end

    def update
        @user = User.find(params[:id])
        if @user.update :email => params.require(:email)
            redirect_to @user
            return
        end
        redirect_to edit_user_path
    end

    def update_password
        @user = User.find(params[:id])
        data = params.require(:data)
        if !@user.checkPassword(data[:current_password])
            flash[:error] = "Wrong password."
            redirect_to edit_password_path
            return
        end
        if data[:password] != data[:confirm_password]
            flash[:error] = "New passwords doesn't match."
            redirect_to edit_password_path
            return
        end
        @user.update_password(data[:password])
        redirect_to @user
    end

    def destroy
        if session[:current_user_id] == nil
            redirect_to root_path
            return
        end
        User.find(session[:current_user_id]).destroy_all
        redirect_to logout_path
    end

    private
        def init_error
            if flash[:error] == nil
                flash[:error] = ""
            end
        end

        def register_params
            params.require(:user).permit(:login, :password, :email)
        end

        def password_check
            pass = params.require(:user).permit(:confirm_password, :password)
            return pass[:confirm_password] == pass[:password]
        end

        def get_login
            params.require(:user).permit(:login)[:login]
        end

        def get_password
            params.require(:user).permit(:password)[:password]
        end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<div class="row  text-center"><h2>Edit</h2></div>
<div class="row ">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <% if flash[:error] != nil %>
            <div class="alert alert-danger"><%= flash[:error] %></div>
        <% end %>
        <%= form_with model: @user, url: user_path, :method => :put do |form| %>
            <div class="form-group">
                <%= form.label :email, "Email: ", class: "control-label" %>
                <%= form.email_field :email, class: "form-control"%>
            </div>
            <%= form.submit 'Save', class: "btn btn-primary" %>
        <% end %>
    </div>
    <div class="col-md-2"></div>
</div>

app/views/users/edit_password.html.erb
<div class="row  text-center"><h2>Change Password</h2></div>
<div class="row ">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <% if flash[:error] != nil %>
            <div class="alert alert-danger"><%= flash[:error] %></div>
        <% end %>
        <%= form_with scope: :data, url: update_password_path, :method => :put do |form| %>
            <div class="form-group">
                <%= form.label :password, "Current password: ", class: "control-label" %>
                <%= form.password_field :current_password, class: "form-control" %>
            </div>
            <div class="form-group">
                <%= form.label :password, "Password: ", class: "control-label" %>
                <%= form.password_field :password, class: "form-control" %>
            </div>
            <div class="form-group">
                <%= form.label :password, "Confirm password: ", class: "control-label" %>
                <%= form.password_field :confirm_password, class: "form-control" %>
            </div>
            <%= form.submit 'Save', class: "btn btn-primary" %>
        <% end %>
    </div>
    <div class="col-md-2"></div>
</div>

app/views/users/get_login_form.html.erb
<div class="row  text-center"><h2>Log In</h2></div>
<div class="row ">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <% if flash[:error] != nil %>
            <div class="alert alert-danger"><%= flash[:error] %></div>
        <% end %>
        <%= form_with scope: :user, url: login_path do |form| %>
            <div class="form-group">
                <%= form.label :login, "Login: ", class: "control-label" %>
                <%= form.text_field :login, class: "form-control", autofocus: "autofocus" %>
            </div>
            <div class="form-group">
                <%= form.label :password, "Password: ", class: "control-label" %>
                <%= form.password_field :password, class: "form-control" %>
            </div>
            <%= form.submit 'Log In', class: "btn btn-primary" %>
        <% end %>
        <p>
         New around here? <%= link_to "Sign Up", new_user_path %>
        </p>
    </div>
    <div class="col-md-2"></div>
</div>

app/views/users/index.html.erb
<div class="container">         
  <table class="table table-dark table-striped">
    <thead>
      <tr>
        <th>Nickname</th>
        <th>Email</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
        <% @users.each do |user| %>
        <tr>
            <td><%= user.login %></td>
            <td><%= user.email %></td>
            <td class="action-buttons">
                <div class="btn-group">
                    <%= link_to "Show Profile", user, :class => "btn btn-success" %>
                </div>
            </td>
        </tr>
        <% end %>
    </tbody>
  </table>
</div>

app/views/users/new.html.erb
<div class="row  text-center"><h2>Sign Up</h2></div>
<div class="row ">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <% if flash[:error] != nil %>
            <div class="alert alert-danger"><%= flash[:error] %></div>
        <% end %>
        <%= form_with scope: :user, url: users_path do |form| %>
            <div class="form-group">
                <%= form.label :login, "Login: ", class: "control-label" %>
                <%= form.text_field :login, class: "form-control", autofocus: "autofocus" %>
            </div>
            <div class="form-group">
                <%= form.label :email, "Email: ", class: "control-label" %>
                <%= form.email_field :email, class: "form-control"%>
            </div>
            <div class="form-group">
                <%= form.label :password, "Password: ", class: "control-label" %>
                <%= form.password_field :password, class: "form-control" %>
            </div>
            <div class="form-group">
                <%= form.label :password, "Confirm password: ", class: "control-label" %>
                <%= form.password_field :confirm_password, class: "form-control" %>
            </div>
            <%= form.submit 'Register', class: "btn btn-primary" %>
        <% end %>
    </div>
    <div class="col-md-2"></div>
</div>

app/views/users/show.html.erb
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <div class="row user-profile">
            <div class="col-md-4 text-center">
                <img src="<%= @user.getGravatarLink(170) %>" class="img-circle" />
                <% if @user[:id] == session[:current_user_id] %>
                    <br/>If you want to change your picture go to <a target="_blank" href="https://www.gravatar.com">Gravatar</a> and create gravatar. 
                <% end %>
            </div>
            <div class="col-md-8">
                <h1><%= @user.login %></h1>
                <h2><%= @user.email %></h2>
                <% if @user[:id] == session[:current_user_id] %>
                <div class="row user-settings">
                    <div class="btn-group">
                        <%= link_to "Edit", edit_user_path, :class => "btn btn-primary" %>
                        <%= link_to "Change Password", edit_password_path, :class => "btn btn-primary" %>
                        <%= link_to "Delete", @user, :method => :delete, :class => "btn btn-danger", 
                                    data: {:confirm => "Are You sure?", :title => "Delete #{@user.login}"} %>
                    </div>
                </div>
                <% end %>
            </div>
        </div>
    </div>
    <div class="col-md-2"></div>
</div>
<div class="row  text-center"><h2>User Leagues</h2></div>
<div class="container">   
  <table class="table table-dark table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
        <% @leagues.find_each do |l| %>
        <tr>
            <td><%= l.name %></td>
            <td class="action-buttons">
                <div class="btn-group">
                  <%= link_to "Show", show_league_path(l), :class => "btn btn-success" %>
                </div>
            </td>
        </tr>
        <% end %>
    </tbody>
  </table>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>