config/routes.rb
Rails.application.routes.draw do
  get 'games/save'
    # Users routes
    resources :users
    get 'login', :to => 'users#get_login_form'
    post 'login', :to => 'users#login'
    get 'logout', :to => 'users#logout'
    get 'users/:id/editpassword', :to => 'users#edit_password', :as => 'edit_password'
    put 'users/:id/password', :to => 'users#update_password', :as => 'update_password'
    # Leagues routes
    get 'leagues', :to => 'leagues#index', :as => 'leagues'
    get 'leagues/new', :to => 'leagues#new', :as => 'new_league'
    post 'leagues', :to => 'leagues#create', :as => 'create_league'
    get 'leagues/:id', :to => 'leagues#show', :as => 'show_league'
    delete 'leagues/:id', :to => 'leagues#destroy', :as => 'destroy_league'
    get 'leagues/add_contestant/:id/:user_id', :to => 'leagues#add_contestant', :as => 'add_contestant'
    get 'leagues/close/:id', :to => 'leagues#close', :as => 'close_league'
    get 'leagues/open/:id', :to => 'leagues#open', :as => 'open_league'
    # Games reoutes
    get 'games/:id', :to => 'games#save', :as => 'save_game_score'
    put 'games/:id', :to => 'games#update', :as => 'update_game'
    # Other routes
    root "welcome#index"
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :league, :class_name => 'League'
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  include GamesHelper
  def save
    @game = Game.find(params[:id])
  end

  def update
    @game = Game.find(params[:id])
    save_score(@game, params.require(:game)[:score_1], params.require(:game)[:score_2])
    add_points(@game)
    redirect_to show_league_path(@game.league)
  end
end

app/helpers/games_helper.rb
module GamesHelper
    def save_score(game, score1, score2)
        game.score_1 = score1
        game.score_2 = score2
        game.is_finished = true
        game.save
        game.league.decrement_games_left
    end

    def add_points(game)
        if game.score_1 == game.score_2
            game.league.contestants.each do |c|
                if c.user.login == game.player_1 || c.user.login == game.player_2
                    c.points += 1
                    c.save
                end
            end
        else
            winner = game.player_1
            if game.score_2 > game.score_1
                winner = game.player_2
            end
            game.league.contestants.each do |c|
                if c.user.login == winner
                    c.points += 2
                    c.save
                end
            end
        end
    end
end

app/views/games/save.html.erb
<div class="row  text-center"><h2>Save game score</h2></div>
<div class="row ">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <%= form_with scope: :game, method: :put, url: update_game_path do |form| %>
            <div class="form-group">
                <%= form.label :score_1, "Scroe for #{@game.player_1}:", class: "control-label" %> 
                <%= form.number_field :score_1, in: 0..1000, class: "form-control" %>
            </div>
            <div class="form-group">
                <%= form.label :score_2, "Scroe for #{@game.player_2}:", class: "control-label" %> 
                <%= form.number_field :score_2, in: 0..1000, class: "form-control" %>
            </div>
            <%= form.submit 'Save', class: "btn btn-primary" %>
        <% end %>
    </div>
    <div class="col-md-2"></div>
</div>