config/routes.rb
Rails.application.routes.draw do
  get 'games/save'
    # Users routes
    resources :users
    get 'login', :to => 'users#get_login_form'
    post 'login', :to => 'users#login'
    get 'logout', :to => 'users#logout'
    get 'users/:id/editpassword', :to => 'users#edit_password', :as => 'edit_password'
    put 'users/:id/password', :to => 'users#update_password', :as => 'update_password'
    # Leagues routes
    get 'leagues', :to => 'leagues#index', :as => 'leagues'
    get 'leagues/new', :to => 'leagues#new', :as => 'new_league'
    post 'leagues', :to => 'leagues#create', :as => 'create_league'
    get 'leagues/:id', :to => 'leagues#show', :as => 'show_league'
    delete 'leagues/:id', :to => 'leagues#destroy', :as => 'destroy_league'
    get 'leagues/add_contestant/:id/:user_id', :to => 'leagues#add_contestant', :as => 'add_contestant'
    get 'leagues/close/:id', :to => 'leagues#close', :as => 'close_league'
    get 'leagues/open/:id', :to => 'leagues#open', :as => 'open_league'
    # Games reoutes
    get 'games/:id', :to => 'games#save', :as => 'save_game_score'
    put 'games/:id', :to => 'games#update', :as => 'update_game'
    # Other routes
    root "welcome#index"
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Leagues App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('favicon.ico'), :rel => 'icon', :type =>  'image/ico' %>
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>                        
        </button>
        <a class="navbar-brand" href="/">Leagues App</a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav">
            <% if session[:current_user_id] != nil %>
            <!-- <li class=""><%= link_to "My Leagues", leagues_path %></li> -->
            <li class=""><%= link_to "All Leagues", leagues_path %></li>
            <li class=""><%= link_to "Active Users", users_path %></li>
            <li class="">
                <%= link_to new_league_path do %>
                    <span class="glyphicon glyphicon-plus"></span> Add League
                <% end %>
            </li>
            <% end %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <% if session[:current_user_id] != nil %>
            <li>
            <%= link_to user_path(session[:current_user_id]) do %>
                <img src="<%= User.find(session[:current_user_id]).getGravatarLink(25) %>" class="img-circle nav-user-icon" />
                <%= session[:current_user_name] %>
            <% end %>
            </li>
            <li><a href="/logout"><span class="glyphicon glyphicon-remove"></span> Log Out</a></li>
            <% else %>
            <li><a href="/users/new"><span class="glyphicon glyphicon-user"></span> Sign In</a></li>
            <li><a href="/login"><span class="glyphicon glyphicon-log-in"></span> Log In</a></li>
            <% end %>
        </ul>
    </div>
</div>
</nav>
<div class="container-fluid text-center">    
<div class="row content">

    <div class="container">
    <%= yield %>
    </div>

</div>
</div>
<footer class="container-fluid text-center">
<p>Copyright © <%= Date.today.year %> Paweł Mstowski</p>
</footer>
<script>
</script>
</body>
</html>